<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW9tKPnb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW9tKPnb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerW9tKPnb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerW9tKPnb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerW9tKPnb\App_KernelDevDebugContainer([
    'container.build_hash' => 'W9tKPnb',
    'container.build_id' => 'c61ca46c',
    'container.build_time' => 1710421889,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW9tKPnb');
